#!/bin/bash

firefox --new-window http://localhost:8080/ &
firefox --new-window http://localhost:9000/ &

# google-chrome --new-window http://localhost:8080/ &
# google-chrome --new-window http://localhost:9000/ &
